### ISSUE TITLE
Install gamman on Mac os x

### ISSUE THREAD

**Issue by HandmannP** [guidov/pygamman#2]
If I try running 
python setup.py install 
I get the error message:
 .... /anaconda2/lib/python2.7/distutils/cmd.py", line 105, in **getattr**
    raise AttributeError, attar
Is there a nice and clean way to get the pygamman running on Mac osx?
Thank you for your help,
Patricia

**Comment by guidov** [comment]
Hi, The setup.py script is not working with Anaconda. I'm still trying to
figure out why

I'll will try to produce some pre-built packages for linux/osx/windows and
upload to anaconda.org so you can easily install it.

To build on OSX the setup may  need xtools and/or  gcc/gfortran
i.e. brew install gcc

If you have a regular python installation the build should work (or a
virtualenv)

**Comment by guidov** [comment]
The problem is with higher versions of numpy (distutils)

I downgraded to numpy version 1.8.2 and the build worked.

——> conda install -y numpy=1.8.2

——> python setup.py build
——> python setup.py install

then

——> conda install -y numpy

to go back to your new version if you like

I'll try OSX at a later date (and building anaconda packages)

**Comment by guidov** [comment]
I tried the above on Mac OSX 10.10 (Yosemite) and it worked. 

Building conda packages may be problematic since there are some paths in the fortran code that are hardcoded to point to some datasets which are moved (during the install) to the install path. These data sets are used by the gamma_n function.

**Comment by HandmannP** [comment]
Thank you it all worked fine!

**Comment by AdrianoGiangiardi** [comment]
Thank you very much guys!!!! I was with same problem.
